/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DefinicoesRouteImport } from './routes/definicoes'
import { Route as DocumentacaoRouteImport } from './routes/documentacao'
import { Route as EncoreAiRouteImport } from './routes/encore-ai'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as BandasIndexRouteImport } from './routes/bandas.index'
import { Route as BandasIdRouteImport } from './routes/bandas.$id'
import { Route as EspetaculosIndexRouteImport } from './routes/espetaculos.index'
import { Route as EspetaculosIdRouteImport } from './routes/espetaculos.$id'
import { Route as MusicosIndexRouteImport } from './routes/musicos.index'
import { Route as MusicosIdRouteImport } from './routes/musicos.$id'
import { Route as RepertorioIndexRouteImport } from './routes/repertorio.index'
import { Route as RepertorioIdRouteImport } from './routes/repertorio.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinicoesRoute = DefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacaoRoute = DocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EncoreAiRoute = EncoreAiRouteImport.update({
  id: '/encore-ai',
  path: '/encore-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const BandasIndexRoute = BandasIndexRouteImport.update({
  id: '/bandas/',
  path: '/bandas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandasIdRoute = BandasIdRouteImport.update({
  id: '/bandas/$id',
  path: '/bandas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EspetaculosIndexRoute = EspetaculosIndexRouteImport.update({
  id: '/espetaculos/',
  path: '/espetaculos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspetaculosIdRoute = EspetaculosIdRouteImport.update({
  id: '/espetaculos/$id',
  path: '/espetaculos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicosIndexRoute = MusicosIndexRouteImport.update({
  id: '/musicos/',
  path: '/musicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicosIdRoute = MusicosIdRouteImport.update({
  id: '/musicos/$id',
  path: '/musicos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertorioIndexRoute = RepertorioIndexRouteImport.update({
  id: '/repertorio/',
  path: '/repertorio/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertorioIdRoute = RepertorioIdRouteImport.update({
  id: '/repertorio/$id',
  path: '/repertorio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/definicoes': typeof DefinicoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/encore-ai': typeof EncoreAiRoute
  '/equipamentos': typeof EquipamentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/live': typeof LiveRoute
  '/marketing': typeof MarketingRoute
  '/roadmap': typeof RoadmapRoute
  '/bandas/$id': typeof BandasIdRoute
  '/espetaculos/$id': typeof EspetaculosIdRoute
  '/musicos/$id': typeof MusicosIdRoute
  '/repertorio/$id': typeof RepertorioIdRoute
  '/bandas/': typeof BandasIndexRoute
  '/espetaculos/': typeof EspetaculosIndexRoute
  '/musicos/': typeof MusicosIndexRoute
  '/repertorio/': typeof RepertorioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/definicoes': typeof DefinicoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/encore-ai': typeof EncoreAiRoute
  '/equipamentos': typeof EquipamentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/live': typeof LiveRoute
  '/marketing': typeof MarketingRoute
  '/roadmap': typeof RoadmapRoute
  '/bandas/$id': typeof BandasIdRoute
  '/espetaculos/$id': typeof EspetaculosIdRoute
  '/musicos/$id': typeof MusicosIdRoute
  '/repertorio/$id': typeof RepertorioIdRoute
  '/bandas': typeof BandasIndexRoute
  '/espetaculos': typeof EspetaculosIndexRoute
  '/musicos': typeof MusicosIndexRoute
  '/repertorio': typeof RepertorioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/definicoes': typeof DefinicoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/encore-ai': typeof EncoreAiRoute
  '/equipamentos': typeof EquipamentosRoute
  '/financeiro': typeof FinanceiroRoute
  '/live': typeof LiveRoute
  '/marketing': typeof MarketingRoute
  '/roadmap': typeof RoadmapRoute
  '/bandas/$id': typeof BandasIdRoute
  '/espetaculos/$id': typeof EspetaculosIdRoute
  '/musicos/$id': typeof MusicosIdRoute
  '/repertorio/$id': typeof RepertorioIdRoute
  '/bandas/': typeof BandasIndexRoute
  '/espetaculos/': typeof EspetaculosIndexRoute
  '/musicos/': typeof MusicosIndexRoute
  '/repertorio/': typeof RepertorioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/contratos'
    | '/crm'
    | '/definicoes'
    | '/documentacao'
    | '/encore-ai'
    | '/equipamentos'
    | '/financeiro'
    | '/live'
    | '/marketing'
    | '/roadmap'
    | '/bandas/$id'
    | '/espetaculos/$id'
    | '/musicos/$id'
    | '/repertorio/$id'
    | '/bandas/'
    | '/espetaculos/'
    | '/musicos/'
    | '/repertorio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/contratos'
    | '/crm'
    | '/definicoes'
    | '/documentacao'
    | '/encore-ai'
    | '/equipamentos'
    | '/financeiro'
    | '/live'
    | '/marketing'
    | '/roadmap'
    | '/bandas/$id'
    | '/espetaculos/$id'
    | '/musicos/$id'
    | '/repertorio/$id'
    | '/bandas'
    | '/espetaculos'
    | '/musicos'
    | '/repertorio'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/contratos'
    | '/crm'
    | '/definicoes'
    | '/documentacao'
    | '/encore-ai'
    | '/equipamentos'
    | '/financeiro'
    | '/live'
    | '/marketing'
    | '/roadmap'
    | '/bandas/$id'
    | '/espetaculos/$id'
    | '/musicos/$id'
    | '/repertorio/$id'
    | '/bandas/'
    | '/espetaculos/'
    | '/musicos/'
    | '/repertorio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ContratosRoute: typeof ContratosRoute
  CrmRoute: typeof CrmRoute
  DefinicoesRoute: typeof DefinicoesRoute
  DocumentacaoRoute: typeof DocumentacaoRoute
  EncoreAiRoute: typeof EncoreAiRoute
  EquipamentosRoute: typeof EquipamentosRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LiveRoute: typeof LiveRoute
  MarketingRoute: typeof MarketingRoute
  RoadmapRoute: typeof RoadmapRoute
  BandasIdRoute: typeof BandasIdRoute
  EspetaculosIdRoute: typeof EspetaculosIdRoute
  MusicosIdRoute: typeof MusicosIdRoute
  RepertorioIdRoute: typeof RepertorioIdRoute
  BandasIndexRoute: typeof BandasIndexRoute
  EspetaculosIndexRoute: typeof EspetaculosIndexRoute
  MusicosIndexRoute: typeof MusicosIndexRoute
  RepertorioIndexRoute: typeof RepertorioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definicoes': {
      id: '/definicoes'
      path: '/definicoes'
      fullPath: '/definicoes'
      preLoaderRoute: typeof DefinicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacao': {
      id: '/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof DocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encore-ai': {
      id: '/encore-ai'
      path: '/encore-ai'
      fullPath: '/encore-ai'
      preLoaderRoute: typeof EncoreAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandas/': {
      id: '/bandas/'
      path: '/bandas'
      fullPath: '/bandas/'
      preLoaderRoute: typeof BandasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandas/$id': {
      id: '/bandas/$id'
      path: '/bandas/$id'
      fullPath: '/bandas/$id'
      preLoaderRoute: typeof BandasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/': {
      id: '/espetaculos/'
      path: '/espetaculos'
      fullPath: '/espetaculos/'
      preLoaderRoute: typeof EspetaculosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espetaculos/$id': {
      id: '/espetaculos/$id'
      path: '/espetaculos/$id'
      fullPath: '/espetaculos/$id'
      preLoaderRoute: typeof EspetaculosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicos/': {
      id: '/musicos/'
      path: '/musicos'
      fullPath: '/musicos/'
      preLoaderRoute: typeof MusicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicos/$id': {
      id: '/musicos/$id'
      path: '/musicos/$id'
      fullPath: '/musicos/$id'
      preLoaderRoute: typeof MusicosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertorio/': {
      id: '/repertorio/'
      path: '/repertorio'
      fullPath: '/repertorio/'
      preLoaderRoute: typeof RepertorioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertorio/$id': {
      id: '/repertorio/$id'
      path: '/repertorio/$id'
      fullPath: '/repertorio/$id'
      preLoaderRoute: typeof RepertorioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ContratosRoute: ContratosRoute,
  CrmRoute: CrmRoute,
  DefinicoesRoute: DefinicoesRoute,
  DocumentacaoRoute: DocumentacaoRoute,
  EncoreAiRoute: EncoreAiRoute,
  EquipamentosRoute: EquipamentosRoute,
  FinanceiroRoute: FinanceiroRoute,
  LiveRoute: LiveRoute,
  MarketingRoute: MarketingRoute,
  RoadmapRoute: RoadmapRoute,
  BandasIdRoute: BandasIdRoute,
  EspetaculosIdRoute: EspetaculosIdRoute,
  MusicosIdRoute: MusicosIdRoute,
  RepertorioIdRoute: RepertorioIdRoute,
  BandasIndexRoute: BandasIndexRoute,
  EspetaculosIndexRoute: EspetaculosIndexRoute,
  MusicosIndexRoute: MusicosIndexRoute,
  RepertorioIndexRoute: RepertorioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
